"""initial schema

Revision ID: f0f984e8f53d
Revises: 
Create Date: 2026-02-12 05:52:14.503851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0f984e8f53d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_limits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('scope_agent_type', sa.String(length=20), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('alert_threshold', sa.Numeric(precision=3, scale=2), server_default='0.80', nullable=False),
    sa.Column('action_on_exceed', sa.String(length=20), server_default='warn', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_on_exceed IN ('warn', 'block')", name='ck_budget_limits_action'),
    sa.CheckConstraint("period IN ('daily', 'weekly', 'monthly')", name='ck_budget_limits_period'),
    sa.CheckConstraint("scope_type IN ('global', 'project', 'agent', 'agent_type')", name='ck_budget_limits_scope_type'),
    sa.CheckConstraint('alert_threshold > 0 AND alert_threshold <= 1.0', name='ck_budget_limits_alert_threshold'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_agent_type', 'budget_limits', ['scope_type', 'scope_agent_type'], unique=False)
    op.create_index('idx_budget_scope', 'budget_limits', ['scope_type', 'scope_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_repo', sa.String(length=255), nullable=False),
    sa.Column('github_app_id', sa.String(length=100), nullable=True),
    sa.Column('github_installation_id', sa.String(length=100), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_github', 'projects', ['github_repo'], unique=False)
    op.create_index('idx_projects_owner', 'projects', ['owner_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('rules_file_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('orchestrator', 'architect', 'coder', 'tester', 'reviewer')", name='ck_agents_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_project', 'agents', ['project_id'], unique=False)
    op.create_index('idx_agents_type', 'agents', ['type'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='5', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhooks_created', 'webhooks', ['created_at'], unique=False)
    op.create_index('idx_webhooks_processed', 'webhooks', ['processed'], unique=False)
    op.create_index('idx_webhooks_project', 'webhooks', ['project_id'], unique=False)
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('importance', sa.Integer(), server_default='5', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 10', name='ck_agent_memory_importance'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'project_id', 'category', 'key', name='uq_agent_memory_key')
    )
    op.create_index('idx_agent_memory_agent', 'agent_memory', ['agent_id'], unique=False)
    op.create_index('idx_agent_memory_expires', 'agent_memory', ['expires_at'], unique=False)
    op.create_index('idx_agent_memory_project', 'agent_memory', ['project_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_agent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'archived')", name='ck_conversations_status'),
    sa.CheckConstraint("type IN ('issue', 'general', 'task', 'review')", name='ck_conversations_type'),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_project', 'conversations', ['project_id'], unique=False)
    op.create_index('idx_conversations_status', 'conversations', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='info', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sent_telegram', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sent_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_notifications_severity'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'agent_id')
    )
    op.create_table('github_issues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_github_issues_project_number')
    )
    op.create_index('idx_issues_conversation', 'github_issues', ['conversation_id'], unique=False)
    op.create_index('idx_issues_project', 'github_issues', ['project_id'], unique=False)
    op.create_index('idx_issues_state', 'github_issues', ['state'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_formatted', sa.Text(), nullable=True),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("author_type IN ('user', 'agent')", name='ck_messages_author_type'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_agent', 'messages', ['agent_id'], unique=False)
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('branch_from', sa.String(length=200), nullable=False),
    sa.Column('branch_to', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('test_status', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_agent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['github_issues.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_pull_requests_project_number')
    )
    op.create_index('idx_prs_agent', 'pull_requests', ['created_by_agent_id'], unique=False)
    op.create_index('idx_prs_issue', 'pull_requests', ['issue_id'], unique=False)
    op.create_index('idx_prs_project', 'pull_requests', ['project_id'], unique=False)
    op.create_index('idx_prs_state', 'pull_requests', ['state'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('assigned_to_agent_id', sa.UUID(), nullable=True),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=True),
    sa.Column('definition_of_done', sa.Text(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='ck_tasks_priority'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'testing', 'review', 'completed', 'failed')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['assigned_to_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['github_issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_agent', 'tasks', ['assigned_to_agent_id'], unique=False)
    op.create_index('idx_tasks_issue', 'tasks', ['issue_id'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_status_priority', 'tasks', ['status', 'priority'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.String(length=20), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('request_duration_ms', sa.Integer(), nullable=True),
    sa.Column('was_cached', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_agent', 'token_usage', ['agent_id'], unique=False)
    op.create_index('idx_token_usage_conversation', 'token_usage', ['conversation_id'], unique=False)
    op.create_index('idx_token_usage_date', 'token_usage', ['usage_date'], unique=False)
    op.create_index('idx_token_usage_project', 'token_usage', ['project_id'], unique=False)
    op.create_index('idx_token_usage_timestamp', 'token_usage', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_usage_timestamp', table_name='token_usage')
    op.drop_index('idx_token_usage_project', table_name='token_usage')
    op.drop_index('idx_token_usage_date', table_name='token_usage')
    op.drop_index('idx_token_usage_conversation', table_name='token_usage')
    op.drop_index('idx_token_usage_agent', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('idx_tasks_status_priority', table_name='tasks')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_issue', table_name='tasks')
    op.drop_index('idx_tasks_agent', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_prs_state', table_name='pull_requests')
    op.drop_index('idx_prs_project', table_name='pull_requests')
    op.drop_index('idx_prs_issue', table_name='pull_requests')
    op.drop_index('idx_prs_agent', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_index('idx_messages_agent', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_issues_state', table_name='github_issues')
    op.drop_index('idx_issues_project', table_name='github_issues')
    op.drop_index('idx_issues_conversation', table_name='github_issues')
    op.drop_table('github_issues')
    op.drop_table('conversation_participants')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_read', table_name='notifications')
    op.drop_index('idx_notifications_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_conversations_status', table_name='conversations')
    op.drop_index('idx_conversations_project', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_agent_memory_project', table_name='agent_memory')
    op.drop_index('idx_agent_memory_expires', table_name='agent_memory')
    op.drop_index('idx_agent_memory_agent', table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index('idx_webhooks_project', table_name='webhooks')
    op.drop_index('idx_webhooks_processed', table_name='webhooks')
    op.drop_index('idx_webhooks_created', table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index('idx_agents_type', table_name='agents')
    op.drop_index('idx_agents_project', table_name='agents')
    op.drop_table('agents')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.drop_index('idx_projects_github', table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_index('idx_budget_scope', table_name='budget_limits')
    op.drop_index('idx_budget_agent_type', table_name='budget_limits')
    op.drop_table('budget_limits')
    # ### end Alembic commands ###
